name: Improvement Request
description: Request an improvement for ServerPackCreator
title: "[Improvement request]: "
labels: ["enhancement"]
assignees:
  - Griefed
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this improvement request!
  - type: textarea
    id: improvement
    attributes:
      label: Whats the feature you would like to be improved?
      description: Describe the improvement of the feature you would like to be made.
      placeholder: Describe, in detail, the improvement of the feature you would like to be made.
      value: "Describe, in detail, the improvement of the feature you would like to be made."
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else you would like to add?
      description: Any additional info you would like to add?
      placeholder: Tell me!
      value: "Tell me!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Griefed/ServerPackCreator/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
